export const timeZones = {
  'America/Noronha': -2,
  'America/Belem': -3,
  'America/Fortaleza': -3,
  'America/Recife': -3,
  'America/Araguaina': -3,
  'America/Maceio': -3,
  'America/Bahia': -3,
  'America/Sao_Paulo': -3,
  'America/Campo_Grande': -4,
  'America/Cuiaba': -4,
  'America/Santarem': -3,
  'America/Porto_Velho': -4,
  'America/Boa_Vista': -4,
  'America/Manaus': -4,
  'America/Eirunepe': -5,
  'America/Rio_Branco': -5,
};
