import { SafeString } from 'aws-sdk/clients/securitylake';
import { LastHourInflux } from '../interfaces';
import { Types } from 'mongoose';

export const influxStub = (): LastHourInflux => {
  return {
    result: '',
    table: 0,
    _start: '',
    _stop: '',
    _time: '',
    _value: 0,
    _field: '',
    _measurement: '',
    dev_id: '',
  };
};

export const influxBucketStub = (clientId?: string) => {
  return {
    _id: new Types.ObjectId('61a8f7d1a1017b2168ce0000'),
    clientId: new Types.ObjectId(clientId || '61a8f7d1a1017b2168ce0000'),
    influxConnectionId: new Types.ObjectId('621689729e30d11efcdb023f'),
    alias: 'Autogenerated hello people bucket',
    product: 'smart-trafo',
    name: 'fox-iot-telemedicao-b',
  };
};

export const qualityStub = () => {
  return { _value: 1, _field: 'drc-', dev_id: 'fxrl-00', result: 'DRP' };
};
